version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  boot-api:
    image: jayendra/boot-starter-api:1.0
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
      - mysql-api
    environment:
      RDS_HOSTNAME: mysql-api
      #RDS_PORT: 3306
      #RDS_DB_NAME: todos
      #RDS_USERNAME: root
      #RDS_PASSWORD: root
    networks:
      - boot-starter-api-network

  mysql-api:
    image: mysql:latest
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer
    volumes:
      - mysql-database-data-volume:/var/lib/mysql-api
    networks:
      - boot-starter-api-network

# Volumes
volumes:
  mysql-database-data-volume:

networks:
  boot-starter-api-network: